sudo: false
language: php
php:
- 5.6
- 7.0
- 7.1
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
env:
  matrix:
   - WP_VERSION=latest WP_MULTISITE=0
   - WP_VERSION=nightly WP_MULTISITE=0
   - WP_VERSION=latest WP_MULTISITE=1
   - WP_VERSION=nightly WP_MULTISITE=1
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- bash bin/prepare.sh
- composer install
script:
- vendor/bin/phpunit
